[package]
name = "calendar_duration"
version = "0.1.1"
authors = ["William R. Fraser <wfraser@codewise.org>"]
edition = "2021"

[dependencies]
chrono = { version = "0.4", optional = true }
time = { version = "0.3", optional = true }

[features]
default = []
