[package]
name = "calendar_duration"
version = "0.1.0"
authors = ["William R. Fraser <wfraser@codewise.org>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", optional = true }
time = { version = "0.2", optional = true }

[features]
default = []
